"""empty message

Revision ID: 2a49e5ef2cbc
Revises: 61c44f34ce7c
Create Date: 2021-12-08 17:31:39.566015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a49e5ef2cbc'
down_revision = '61c44f34ce7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint('_ticket_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_unique_constraint('_ticket_uc', ['name', 'username', 'department'])

    # ### end Alembic commands ###
