"""empty message

Revision ID: f6f1f8ea9d62
Revises: 2a49e5ef2cbc
Create Date: 2021-12-12 20:33:06.521800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f1f8ea9d62'
down_revision = '2a49e5ef2cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_timestamp')

    op.drop_table('history')
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_served', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('_ticket_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.create_unique_constraint('_ticket_uc', ['name', 'username', 'department'])
        batch_op.drop_column('was_served')

    op.create_table('history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('ix_history_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
